# SDK 最低支持版本为 iOS 8.0
platform:ios, '8.0'

# github 官方 pod 源
source 'https://github.com/CocoaPods/Specs.git'
# 阿里云 pod 源
source 'https://github.com/aliyun/aliyun-specs.git'

# 需要替换下述 "IMSDemoApp" 为开发者 App 的 target 名称
target "smartlight" do
    pod 'AlicloudALBBOpenAccount', '3.4.0.26'
    pod 'IMSApiClient', '1.1.0'
    pod 'IMSAuthentication', '1.0.0'
    pod 'IMSBreezeSDK', '1.0.0'
    pod 'IMSBoneKit', '1.1.0'
    pod 'AKReactNative', '0.41.2'
    pod 'MJRefresh', '3.1.15'
    pod 'ZipArchive', '1.4.0'
    pod 'IMSDeviceGateway', '1.1.0'
    pod 'OpenSSL', '1.0.208'
    pod 'IMSDeviceCenter', '1.0.0'
    pod 'CocoaAsyncSocket', '7.4.2'
    pod 'Reachability', '3.2'
    pod 'IMSThingCapability', '1.0.0'
    pod 'AlicloudPushIoT', '1.9.5.3'
    pod 'IMSMobileChannel', '1.1.0'
end
